name: Upload Repository as Artifact

on:
  workflow_dispatch

jobs:
  zip_and_upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload Zip
        uses: actions/upload-artifact@v4
        with:
          name: ts-package
          path: .
          
